// GENERATED CODE -- DO NOT EDIT!
// Generated by scripts/generate-protobus-setup.mjs
import * as proto from "@shared/proto/index";
import { ProtoBusClient, Callbacks } from "./grpc-client-base";

export class AccountServiceClient extends ProtoBusClient {
	static override serviceName: string = "dietcode.AccountService";
	static async accountLoginClicked(
		request: proto.dietcode.EmptyRequest,
	): Promise<proto.dietcode.String> {
		return this.makeUnaryRequest(
			"accountLoginClicked",
			request,
			proto.dietcode.EmptyRequest.toJSON,
			proto.dietcode.String.fromJSON,
		);
	}
	static async accountLogoutClicked(
		request: proto.dietcode.EmptyRequest,
	): Promise<proto.dietcode.Empty> {
		return this.makeUnaryRequest(
			"accountLogoutClicked",
			request,
			proto.dietcode.EmptyRequest.toJSON,
			proto.dietcode.Empty.fromJSON,
		);
	}
	static subscribeToAuthStatusUpdate(
		request: proto.dietcode.EmptyRequest,
		callbacks: Callbacks<proto.dietcode.AuthState>,
	): () => void {
		return this.makeStreamingRequest(
			"subscribeToAuthStatusUpdate",
			request,
			proto.dietcode.EmptyRequest.toJSON,
			proto.dietcode.AuthState.fromJSON,
			callbacks,
		);
	}
	static async authStateChanged(
		request: proto.dietcode.AuthStateChangedRequest,
	): Promise<proto.dietcode.AuthState> {
		return this.makeUnaryRequest(
			"authStateChanged",
			request,
			proto.dietcode.AuthStateChangedRequest.toJSON,
			proto.dietcode.AuthState.fromJSON,
		);
	}
	static async getUserCredits(
		request: proto.dietcode.EmptyRequest,
	): Promise<proto.dietcode.UserCreditsData> {
		return this.makeUnaryRequest(
			"getUserCredits",
			request,
			proto.dietcode.EmptyRequest.toJSON,
			proto.dietcode.UserCreditsData.fromJSON,
		);
	}
	static async getOrganizationCredits(
		request: proto.dietcode.GetOrganizationCreditsRequest,
	): Promise<proto.dietcode.OrganizationCreditsData> {
		return this.makeUnaryRequest(
			"getOrganizationCredits",
			request,
			proto.dietcode.GetOrganizationCreditsRequest.toJSON,
			proto.dietcode.OrganizationCreditsData.fromJSON,
		);
	}
	static async getUserOrganizations(
		request: proto.dietcode.EmptyRequest,
	): Promise<proto.dietcode.UserOrganizationsResponse> {
		return this.makeUnaryRequest(
			"getUserOrganizations",
			request,
			proto.dietcode.EmptyRequest.toJSON,
			proto.dietcode.UserOrganizationsResponse.fromJSON,
		);
	}
	static async setUserOrganization(
		request: proto.dietcode.UserOrganizationUpdateRequest,
	): Promise<proto.dietcode.Empty> {
		return this.makeUnaryRequest(
			"setUserOrganization",
			request,
			proto.dietcode.UserOrganizationUpdateRequest.toJSON,
			proto.dietcode.Empty.fromJSON,
		);
	}
	static async openrouterAuthClicked(
		request: proto.dietcode.EmptyRequest,
	): Promise<proto.dietcode.Empty> {
		return this.makeUnaryRequest(
			"openrouterAuthClicked",
			request,
			proto.dietcode.EmptyRequest.toJSON,
			proto.dietcode.Empty.fromJSON,
		);
	}
	static async requestyAuthClicked(
		request: proto.dietcode.StringRequest,
	): Promise<proto.dietcode.Empty> {
		return this.makeUnaryRequest(
			"requestyAuthClicked",
			request,
			proto.dietcode.StringRequest.toJSON,
			proto.dietcode.Empty.fromJSON,
		);
	}
	static async hicapAuthClicked(
		request: proto.dietcode.EmptyRequest,
	): Promise<proto.dietcode.Empty> {
		return this.makeUnaryRequest(
			"hicapAuthClicked",
			request,
			proto.dietcode.EmptyRequest.toJSON,
			proto.dietcode.Empty.fromJSON,
		);
	}
	static async googleAuthClicked(
		request: proto.dietcode.EmptyRequest,
	): Promise<proto.dietcode.Empty> {
		return this.makeUnaryRequest(
			"googleAuthClicked",
			request,
			proto.dietcode.EmptyRequest.toJSON,
			proto.dietcode.Empty.fromJSON,
		);
	}
	static async getRedirectUrl(
		request: proto.dietcode.EmptyRequest,
	): Promise<proto.dietcode.String> {
		return this.makeUnaryRequest(
			"getRedirectUrl",
			request,
			proto.dietcode.EmptyRequest.toJSON,
			proto.dietcode.String.fromJSON,
		);
	}
	static async openAiCodexSignIn(
		request: proto.dietcode.EmptyRequest,
	): Promise<proto.dietcode.Empty> {
		return this.makeUnaryRequest(
			"openAiCodexSignIn",
			request,
			proto.dietcode.EmptyRequest.toJSON,
			proto.dietcode.Empty.fromJSON,
		);
	}
	static async openAiCodexSignOut(
		request: proto.dietcode.EmptyRequest,
	): Promise<proto.dietcode.Empty> {
		return this.makeUnaryRequest(
			"openAiCodexSignOut",
			request,
			proto.dietcode.EmptyRequest.toJSON,
			proto.dietcode.Empty.fromJSON,
		);
	}
	static async xaiOauthSignIn(
		request: proto.dietcode.EmptyRequest,
	): Promise<proto.dietcode.Empty> {
		return this.makeUnaryRequest(
			"xaiOauthSignIn",
			request,
			proto.dietcode.EmptyRequest.toJSON,
			proto.dietcode.Empty.fromJSON,
		);
	}
	static async xaiOauthSignOut(
		request: proto.dietcode.EmptyRequest,
	): Promise<proto.dietcode.Empty> {
		return this.makeUnaryRequest(
			"xaiOauthSignOut",
			request,
			proto.dietcode.EmptyRequest.toJSON,
			proto.dietcode.Empty.fromJSON,
		);
	}
	static async googleSignOutClicked(
		request: proto.dietcode.EmptyRequest,
	): Promise<proto.dietcode.Empty> {
		return this.makeUnaryRequest(
			"googleSignOutClicked",
			request,
			proto.dietcode.EmptyRequest.toJSON,
			proto.dietcode.Empty.fromJSON,
		);
	}
}
export class BrowserServiceClient extends ProtoBusClient {
	static override serviceName: string = "dietcode.BrowserService";
	static async getBrowserConnectionInfo(
		request: proto.dietcode.EmptyRequest,
	): Promise<proto.dietcode.BrowserConnectionInfo> {
		return this.makeUnaryRequest(
			"getBrowserConnectionInfo",
			request,
			proto.dietcode.EmptyRequest.toJSON,
			proto.dietcode.BrowserConnectionInfo.fromJSON,
		);
	}
	static async testBrowserConnection(
		request: proto.dietcode.StringRequest,
	): Promise<proto.dietcode.BrowserConnection> {
		return this.makeUnaryRequest(
			"testBrowserConnection",
			request,
			proto.dietcode.StringRequest.toJSON,
			proto.dietcode.BrowserConnection.fromJSON,
		);
	}
	static async discoverBrowser(
		request: proto.dietcode.EmptyRequest,
	): Promise<proto.dietcode.BrowserConnection> {
		return this.makeUnaryRequest(
			"discoverBrowser",
			request,
			proto.dietcode.EmptyRequest.toJSON,
			proto.dietcode.BrowserConnection.fromJSON,
		);
	}
	static async getDetectedChromePath(
		request: proto.dietcode.EmptyRequest,
	): Promise<proto.dietcode.ChromePath> {
		return this.makeUnaryRequest(
			"getDetectedChromePath",
			request,
			proto.dietcode.EmptyRequest.toJSON,
			proto.dietcode.ChromePath.fromJSON,
		);
	}
	static async relaunchChromeDebugMode(
		request: proto.dietcode.EmptyRequest,
	): Promise<proto.dietcode.String> {
		return this.makeUnaryRequest(
			"relaunchChromeDebugMode",
			request,
			proto.dietcode.EmptyRequest.toJSON,
			proto.dietcode.String.fromJSON,
		);
	}
}
export class CheckpointsServiceClient extends ProtoBusClient {
	static override serviceName: string = "dietcode.CheckpointsService";
	static async checkpointDiff(
		request: proto.dietcode.Int64Request,
	): Promise<proto.dietcode.Empty> {
		return this.makeUnaryRequest(
			"checkpointDiff",
			request,
			proto.dietcode.Int64Request.toJSON,
			proto.dietcode.Empty.fromJSON,
		);
	}
	static async checkpointRestore(
		request: proto.dietcode.CheckpointRestoreRequest,
	): Promise<proto.dietcode.Empty> {
		return this.makeUnaryRequest(
			"checkpointRestore",
			request,
			proto.dietcode.CheckpointRestoreRequest.toJSON,
			proto.dietcode.Empty.fromJSON,
		);
	}
	static subscribeToCheckpoints(
		request: proto.dietcode.CheckpointSubscriptionRequest,
		callbacks: Callbacks<proto.dietcode.CheckpointEvent>,
	): () => void {
		return this.makeStreamingRequest(
			"subscribeToCheckpoints",
			request,
			proto.dietcode.CheckpointSubscriptionRequest.toJSON,
			proto.dietcode.CheckpointEvent.fromJSON,
			callbacks,
		);
	}
	static async getCwdHash(
		request: proto.dietcode.StringArrayRequest,
	): Promise<proto.dietcode.PathHashMap> {
		return this.makeUnaryRequest(
			"getCwdHash",
			request,
			proto.dietcode.StringArrayRequest.toJSON,
			proto.dietcode.PathHashMap.fromJSON,
		);
	}
}
export class CommandsServiceClient extends ProtoBusClient {
	static override serviceName: string = "dietcode.CommandsService";
	static async addToDietCode(
		request: proto.dietcode.CommandContext,
	): Promise<proto.dietcode.Empty> {
		return this.makeUnaryRequest(
			"addToDietCode",
			request,
			proto.dietcode.CommandContext.toJSON,
			proto.dietcode.Empty.fromJSON,
		);
	}
	static async fixWithDietCode(
		request: proto.dietcode.CommandContext,
	): Promise<proto.dietcode.Empty> {
		return this.makeUnaryRequest(
			"fixWithDietCode",
			request,
			proto.dietcode.CommandContext.toJSON,
			proto.dietcode.Empty.fromJSON,
		);
	}
	static async explainWithDietCode(
		request: proto.dietcode.CommandContext,
	): Promise<proto.dietcode.Empty> {
		return this.makeUnaryRequest(
			"explainWithDietCode",
			request,
			proto.dietcode.CommandContext.toJSON,
			proto.dietcode.Empty.fromJSON,
		);
	}
	static async improveWithDietCode(
		request: proto.dietcode.CommandContext,
	): Promise<proto.dietcode.Empty> {
		return this.makeUnaryRequest(
			"improveWithDietCode",
			request,
			proto.dietcode.CommandContext.toJSON,
			proto.dietcode.Empty.fromJSON,
		);
	}
}
export class FileServiceClient extends ProtoBusClient {
	static override serviceName: string = "dietcode.FileService";
	static async copyToClipboard(
		request: proto.dietcode.StringRequest,
	): Promise<proto.dietcode.Empty> {
		return this.makeUnaryRequest(
			"copyToClipboard",
			request,
			proto.dietcode.StringRequest.toJSON,
			proto.dietcode.Empty.fromJSON,
		);
	}
	static async openFile(
		request: proto.dietcode.StringRequest,
	): Promise<proto.dietcode.Empty> {
		return this.makeUnaryRequest(
			"openFile",
			request,
			proto.dietcode.StringRequest.toJSON,
			proto.dietcode.Empty.fromJSON,
		);
	}
	static async openImage(
		request: proto.dietcode.StringRequest,
	): Promise<proto.dietcode.Empty> {
		return this.makeUnaryRequest(
			"openImage",
			request,
			proto.dietcode.StringRequest.toJSON,
			proto.dietcode.Empty.fromJSON,
		);
	}
	static async openMention(
		request: proto.dietcode.StringRequest,
	): Promise<proto.dietcode.Empty> {
		return this.makeUnaryRequest(
			"openMention",
			request,
			proto.dietcode.StringRequest.toJSON,
			proto.dietcode.Empty.fromJSON,
		);
	}
	static async deleteRuleFile(
		request: proto.dietcode.RuleFileRequest,
	): Promise<proto.dietcode.RuleFile> {
		return this.makeUnaryRequest(
			"deleteRuleFile",
			request,
			proto.dietcode.RuleFileRequest.toJSON,
			proto.dietcode.RuleFile.fromJSON,
		);
	}
	static async createRuleFile(
		request: proto.dietcode.RuleFileRequest,
	): Promise<proto.dietcode.RuleFile> {
		return this.makeUnaryRequest(
			"createRuleFile",
			request,
			proto.dietcode.RuleFileRequest.toJSON,
			proto.dietcode.RuleFile.fromJSON,
		);
	}
	static async searchCommits(
		request: proto.dietcode.StringRequest,
	): Promise<proto.dietcode.GitCommits> {
		return this.makeUnaryRequest(
			"searchCommits",
			request,
			proto.dietcode.StringRequest.toJSON,
			proto.dietcode.GitCommits.fromJSON,
		);
	}
	static async selectFiles(
		request: proto.dietcode.BooleanRequest,
	): Promise<proto.dietcode.StringArrays> {
		return this.makeUnaryRequest(
			"selectFiles",
			request,
			proto.dietcode.BooleanRequest.toJSON,
			proto.dietcode.StringArrays.fromJSON,
		);
	}
	static async getRelativePaths(
		request: proto.dietcode.RelativePathsRequest,
	): Promise<proto.dietcode.RelativePaths> {
		return this.makeUnaryRequest(
			"getRelativePaths",
			request,
			proto.dietcode.RelativePathsRequest.toJSON,
			proto.dietcode.RelativePaths.fromJSON,
		);
	}
	static async searchFiles(
		request: proto.dietcode.FileSearchRequest,
	): Promise<proto.dietcode.FileSearchResults> {
		return this.makeUnaryRequest(
			"searchFiles",
			request,
			proto.dietcode.FileSearchRequest.toJSON,
			proto.dietcode.FileSearchResults.fromJSON,
		);
	}
	static async toggleDietCodeRule(
		request: proto.dietcode.ToggleDietCodeRuleRequest,
	): Promise<proto.dietcode.ToggleDietCodeRules> {
		return this.makeUnaryRequest(
			"toggleDietCodeRule",
			request,
			proto.dietcode.ToggleDietCodeRuleRequest.toJSON,
			proto.dietcode.ToggleDietCodeRules.fromJSON,
		);
	}
	static async toggleCursorRule(
		request: proto.dietcode.ToggleCursorRuleRequest,
	): Promise<proto.dietcode.DietCodeRulesToggles> {
		return this.makeUnaryRequest(
			"toggleCursorRule",
			request,
			proto.dietcode.ToggleCursorRuleRequest.toJSON,
			proto.dietcode.DietCodeRulesToggles.fromJSON,
		);
	}
	static async toggleWindsurfRule(
		request: proto.dietcode.ToggleWindsurfRuleRequest,
	): Promise<proto.dietcode.DietCodeRulesToggles> {
		return this.makeUnaryRequest(
			"toggleWindsurfRule",
			request,
			proto.dietcode.ToggleWindsurfRuleRequest.toJSON,
			proto.dietcode.DietCodeRulesToggles.fromJSON,
		);
	}
	static async toggleAgentsRule(
		request: proto.dietcode.ToggleAgentsRuleRequest,
	): Promise<proto.dietcode.DietCodeRulesToggles> {
		return this.makeUnaryRequest(
			"toggleAgentsRule",
			request,
			proto.dietcode.ToggleAgentsRuleRequest.toJSON,
			proto.dietcode.DietCodeRulesToggles.fromJSON,
		);
	}
	static async refreshRules(
		request: proto.dietcode.EmptyRequest,
	): Promise<proto.dietcode.RefreshedRules> {
		return this.makeUnaryRequest(
			"refreshRules",
			request,
			proto.dietcode.EmptyRequest.toJSON,
			proto.dietcode.RefreshedRules.fromJSON,
		);
	}
	static async openDiskConversationHistory(
		request: proto.dietcode.StringRequest,
	): Promise<proto.dietcode.Empty> {
		return this.makeUnaryRequest(
			"openDiskConversationHistory",
			request,
			proto.dietcode.StringRequest.toJSON,
			proto.dietcode.Empty.fromJSON,
		);
	}
	static async toggleWorkflow(
		request: proto.dietcode.ToggleWorkflowRequest,
	): Promise<proto.dietcode.DietCodeRulesToggles> {
		return this.makeUnaryRequest(
			"toggleWorkflow",
			request,
			proto.dietcode.ToggleWorkflowRequest.toJSON,
			proto.dietcode.DietCodeRulesToggles.fromJSON,
		);
	}
	static async ifFileExistsRelativePath(
		request: proto.dietcode.StringRequest,
	): Promise<proto.dietcode.BooleanResponse> {
		return this.makeUnaryRequest(
			"ifFileExistsRelativePath",
			request,
			proto.dietcode.StringRequest.toJSON,
			proto.dietcode.BooleanResponse.fromJSON,
		);
	}
	static async openFileRelativePath(
		request: proto.dietcode.StringRequest,
	): Promise<proto.dietcode.Empty> {
		return this.makeUnaryRequest(
			"openFileRelativePath",
			request,
			proto.dietcode.StringRequest.toJSON,
			proto.dietcode.Empty.fromJSON,
		);
	}
	static async openFocusChainFile(
		request: proto.dietcode.StringRequest,
	): Promise<proto.dietcode.Empty> {
		return this.makeUnaryRequest(
			"openFocusChainFile",
			request,
			proto.dietcode.StringRequest.toJSON,
			proto.dietcode.Empty.fromJSON,
		);
	}
	static async refreshHooks(
		request: proto.dietcode.EmptyRequest,
	): Promise<proto.dietcode.HooksToggles> {
		return this.makeUnaryRequest(
			"refreshHooks",
			request,
			proto.dietcode.EmptyRequest.toJSON,
			proto.dietcode.HooksToggles.fromJSON,
		);
	}
	static async toggleHook(
		request: proto.dietcode.ToggleHookRequest,
	): Promise<proto.dietcode.ToggleHookResponse> {
		return this.makeUnaryRequest(
			"toggleHook",
			request,
			proto.dietcode.ToggleHookRequest.toJSON,
			proto.dietcode.ToggleHookResponse.fromJSON,
		);
	}
	static async createHook(
		request: proto.dietcode.CreateHookRequest,
	): Promise<proto.dietcode.CreateHookResponse> {
		return this.makeUnaryRequest(
			"createHook",
			request,
			proto.dietcode.CreateHookRequest.toJSON,
			proto.dietcode.CreateHookResponse.fromJSON,
		);
	}
	static async deleteHook(
		request: proto.dietcode.DeleteHookRequest,
	): Promise<proto.dietcode.DeleteHookResponse> {
		return this.makeUnaryRequest(
			"deleteHook",
			request,
			proto.dietcode.DeleteHookRequest.toJSON,
			proto.dietcode.DeleteHookResponse.fromJSON,
		);
	}
	static async refreshSkills(
		request: proto.dietcode.EmptyRequest,
	): Promise<proto.dietcode.RefreshedSkills> {
		return this.makeUnaryRequest(
			"refreshSkills",
			request,
			proto.dietcode.EmptyRequest.toJSON,
			proto.dietcode.RefreshedSkills.fromJSON,
		);
	}
	static async toggleSkill(
		request: proto.dietcode.ToggleSkillRequest,
	): Promise<proto.dietcode.SkillsToggles> {
		return this.makeUnaryRequest(
			"toggleSkill",
			request,
			proto.dietcode.ToggleSkillRequest.toJSON,
			proto.dietcode.SkillsToggles.fromJSON,
		);
	}
	static async createSkillFile(
		request: proto.dietcode.CreateSkillRequest,
	): Promise<proto.dietcode.SkillsToggles> {
		return this.makeUnaryRequest(
			"createSkillFile",
			request,
			proto.dietcode.CreateSkillRequest.toJSON,
			proto.dietcode.SkillsToggles.fromJSON,
		);
	}
	static async deleteSkillFile(
		request: proto.dietcode.DeleteSkillRequest,
	): Promise<proto.dietcode.SkillsToggles> {
		return this.makeUnaryRequest(
			"deleteSkillFile",
			request,
			proto.dietcode.DeleteSkillRequest.toJSON,
			proto.dietcode.SkillsToggles.fromJSON,
		);
	}
}
export class JoyZoningServiceClient extends ProtoBusClient {
	static override serviceName: string = "dietcode.JoyZoningService";
	static triggerAudit(
		request: proto.dietcode.JoyZoningAuditRequest,
		callbacks: Callbacks<proto.dietcode.JoyZoningAuditResponse>,
	): () => void {
		return this.makeStreamingRequest(
			"triggerAudit",
			request,
			proto.dietcode.JoyZoningAuditRequest.toJSON,
			proto.dietcode.JoyZoningAuditResponse.fromJSON,
			callbacks,
		);
	}
	static async executeRefactor(
		request: proto.dietcode.JoyZoningRefactorRequest,
	): Promise<proto.dietcode.JoyZoningRefactorResponse> {
		return this.makeUnaryRequest(
			"executeRefactor",
			request,
			proto.dietcode.JoyZoningRefactorRequest.toJSON,
			proto.dietcode.JoyZoningRefactorResponse.fromJSON,
		);
	}
	static async executeBatchRefactor(
		request: proto.dietcode.JoyZoningBatchRefactorRequest,
	): Promise<proto.dietcode.JoyZoningBatchRefactorResponse> {
		return this.makeUnaryRequest(
			"executeBatchRefactor",
			request,
			proto.dietcode.JoyZoningBatchRefactorRequest.toJSON,
			proto.dietcode.JoyZoningBatchRefactorResponse.fromJSON,
		);
	}
}
export class McpServiceClient extends ProtoBusClient {
	static override serviceName: string = "dietcode.McpService";
	static async toggleMcpServer(
		request: proto.dietcode.ToggleMcpServerRequest,
	): Promise<proto.dietcode.McpServers> {
		return this.makeUnaryRequest(
			"toggleMcpServer",
			request,
			proto.dietcode.ToggleMcpServerRequest.toJSON,
			proto.dietcode.McpServers.fromJSON,
		);
	}
	static async updateMcpTimeout(
		request: proto.dietcode.UpdateMcpTimeoutRequest,
	): Promise<proto.dietcode.McpServers> {
		return this.makeUnaryRequest(
			"updateMcpTimeout",
			request,
			proto.dietcode.UpdateMcpTimeoutRequest.toJSON,
			proto.dietcode.McpServers.fromJSON,
		);
	}
	static async addRemoteMcpServer(
		request: proto.dietcode.AddRemoteMcpServerRequest,
	): Promise<proto.dietcode.McpServers> {
		return this.makeUnaryRequest(
			"addRemoteMcpServer",
			request,
			proto.dietcode.AddRemoteMcpServerRequest.toJSON,
			proto.dietcode.McpServers.fromJSON,
		);
	}
	static async downloadMcp(
		request: proto.dietcode.StringRequest,
	): Promise<proto.dietcode.McpDownloadResponse> {
		return this.makeUnaryRequest(
			"downloadMcp",
			request,
			proto.dietcode.StringRequest.toJSON,
			proto.dietcode.McpDownloadResponse.fromJSON,
		);
	}
	static async restartMcpServer(
		request: proto.dietcode.StringRequest,
	): Promise<proto.dietcode.McpServers> {
		return this.makeUnaryRequest(
			"restartMcpServer",
			request,
			proto.dietcode.StringRequest.toJSON,
			proto.dietcode.McpServers.fromJSON,
		);
	}
	static async deleteMcpServer(
		request: proto.dietcode.StringRequest,
	): Promise<proto.dietcode.McpServers> {
		return this.makeUnaryRequest(
			"deleteMcpServer",
			request,
			proto.dietcode.StringRequest.toJSON,
			proto.dietcode.McpServers.fromJSON,
		);
	}
	static async toggleToolAutoApprove(
		request: proto.dietcode.ToggleToolAutoApproveRequest,
	): Promise<proto.dietcode.McpServers> {
		return this.makeUnaryRequest(
			"toggleToolAutoApprove",
			request,
			proto.dietcode.ToggleToolAutoApproveRequest.toJSON,
			proto.dietcode.McpServers.fromJSON,
		);
	}
	static async refreshMcpMarketplace(
		request: proto.dietcode.EmptyRequest,
	): Promise<proto.dietcode.McpMarketplaceCatalog> {
		return this.makeUnaryRequest(
			"refreshMcpMarketplace",
			request,
			proto.dietcode.EmptyRequest.toJSON,
			proto.dietcode.McpMarketplaceCatalog.fromJSON,
		);
	}
	static async openMcpSettings(
		request: proto.dietcode.EmptyRequest,
	): Promise<proto.dietcode.Empty> {
		return this.makeUnaryRequest(
			"openMcpSettings",
			request,
			proto.dietcode.EmptyRequest.toJSON,
			proto.dietcode.Empty.fromJSON,
		);
	}
	static async authenticateMcpServer(
		request: proto.dietcode.StringRequest,
	): Promise<proto.dietcode.Empty> {
		return this.makeUnaryRequest(
			"authenticateMcpServer",
			request,
			proto.dietcode.StringRequest.toJSON,
			proto.dietcode.Empty.fromJSON,
		);
	}
	static subscribeToMcpMarketplaceCatalog(
		request: proto.dietcode.EmptyRequest,
		callbacks: Callbacks<proto.dietcode.McpMarketplaceCatalog>,
	): () => void {
		return this.makeStreamingRequest(
			"subscribeToMcpMarketplaceCatalog",
			request,
			proto.dietcode.EmptyRequest.toJSON,
			proto.dietcode.McpMarketplaceCatalog.fromJSON,
			callbacks,
		);
	}
	static async getLatestMcpServers(
		request: proto.dietcode.Empty,
	): Promise<proto.dietcode.McpServers> {
		return this.makeUnaryRequest(
			"getLatestMcpServers",
			request,
			proto.dietcode.Empty.toJSON,
			proto.dietcode.McpServers.fromJSON,
		);
	}
	static subscribeToMcpServers(
		request: proto.dietcode.EmptyRequest,
		callbacks: Callbacks<proto.dietcode.McpServers>,
	): () => void {
		return this.makeStreamingRequest(
			"subscribeToMcpServers",
			request,
			proto.dietcode.EmptyRequest.toJSON,
			proto.dietcode.McpServers.fromJSON,
			callbacks,
		);
	}
}
export class ModelsServiceClient extends ProtoBusClient {
	static override serviceName: string = "dietcode.ModelsService";
	static async getOllamaModels(
		request: proto.dietcode.StringRequest,
	): Promise<proto.dietcode.StringArray> {
		return this.makeUnaryRequest(
			"getOllamaModels",
			request,
			proto.dietcode.StringRequest.toJSON,
			proto.dietcode.StringArray.fromJSON,
		);
	}
	static async getLmStudioModels(
		request: proto.dietcode.StringRequest,
	): Promise<proto.dietcode.StringArray> {
		return this.makeUnaryRequest(
			"getLmStudioModels",
			request,
			proto.dietcode.StringRequest.toJSON,
			proto.dietcode.StringArray.fromJSON,
		);
	}
	static async getVsCodeLmModels(
		request: proto.dietcode.EmptyRequest,
	): Promise<proto.dietcode.VsCodeLmModelsArray> {
		return this.makeUnaryRequest(
			"getVsCodeLmModels",
			request,
			proto.dietcode.EmptyRequest.toJSON,
			proto.dietcode.VsCodeLmModelsArray.fromJSON,
		);
	}
	static async refreshOpenRouterModelsRpc(
		request: proto.dietcode.EmptyRequest,
	): Promise<proto.dietcode.OpenRouterCompatibleModelInfo> {
		return this.makeUnaryRequest(
			"refreshOpenRouterModelsRpc",
			request,
			proto.dietcode.EmptyRequest.toJSON,
			proto.dietcode.OpenRouterCompatibleModelInfo.fromJSON,
		);
	}
	static async refreshDietCodeRecommendedModelsRpc(
		request: proto.dietcode.EmptyRequest,
	): Promise<proto.dietcode.DietCodeRecommendedModelsResponse> {
		return this.makeUnaryRequest(
			"refreshDietCodeRecommendedModelsRpc",
			request,
			proto.dietcode.EmptyRequest.toJSON,
			proto.dietcode.DietCodeRecommendedModelsResponse.fromJSON,
		);
	}
	static async refreshDietCodeModelsRpc(
		request: proto.dietcode.EmptyRequest,
	): Promise<proto.dietcode.OpenRouterCompatibleModelInfo> {
		return this.makeUnaryRequest(
			"refreshDietCodeModelsRpc",
			request,
			proto.dietcode.EmptyRequest.toJSON,
			proto.dietcode.OpenRouterCompatibleModelInfo.fromJSON,
		);
	}
	static async refreshHuggingFaceModels(
		request: proto.dietcode.EmptyRequest,
	): Promise<proto.dietcode.OpenRouterCompatibleModelInfo> {
		return this.makeUnaryRequest(
			"refreshHuggingFaceModels",
			request,
			proto.dietcode.EmptyRequest.toJSON,
			proto.dietcode.OpenRouterCompatibleModelInfo.fromJSON,
		);
	}
	static async refreshOpenAiModels(
		request: proto.dietcode.OpenAiModelsRequest,
	): Promise<proto.dietcode.StringArray> {
		return this.makeUnaryRequest(
			"refreshOpenAiModels",
			request,
			proto.dietcode.OpenAiModelsRequest.toJSON,
			proto.dietcode.StringArray.fromJSON,
		);
	}
	static async refreshRequestyModels(
		request: proto.dietcode.EmptyRequest,
	): Promise<proto.dietcode.OpenRouterCompatibleModelInfo> {
		return this.makeUnaryRequest(
			"refreshRequestyModels",
			request,
			proto.dietcode.EmptyRequest.toJSON,
			proto.dietcode.OpenRouterCompatibleModelInfo.fromJSON,
		);
	}
	static async refreshHicapModels(
		request: proto.dietcode.EmptyRequest,
	): Promise<proto.dietcode.OpenRouterCompatibleModelInfo> {
		return this.makeUnaryRequest(
			"refreshHicapModels",
			request,
			proto.dietcode.EmptyRequest.toJSON,
			proto.dietcode.OpenRouterCompatibleModelInfo.fromJSON,
		);
	}
	static async refreshLiteLlmModelsRpc(
		request: proto.dietcode.EmptyRequest,
	): Promise<proto.dietcode.OpenRouterCompatibleModelInfo> {
		return this.makeUnaryRequest(
			"refreshLiteLlmModelsRpc",
			request,
			proto.dietcode.EmptyRequest.toJSON,
			proto.dietcode.OpenRouterCompatibleModelInfo.fromJSON,
		);
	}
	static subscribeToOpenRouterModels(
		request: proto.dietcode.EmptyRequest,
		callbacks: Callbacks<proto.dietcode.OpenRouterCompatibleModelInfo>,
	): () => void {
		return this.makeStreamingRequest(
			"subscribeToOpenRouterModels",
			request,
			proto.dietcode.EmptyRequest.toJSON,
			proto.dietcode.OpenRouterCompatibleModelInfo.fromJSON,
			callbacks,
		);
	}
	static subscribeToLiteLlmModels(
		request: proto.dietcode.EmptyRequest,
		callbacks: Callbacks<proto.dietcode.OpenRouterCompatibleModelInfo>,
	): () => void {
		return this.makeStreamingRequest(
			"subscribeToLiteLlmModels",
			request,
			proto.dietcode.EmptyRequest.toJSON,
			proto.dietcode.OpenRouterCompatibleModelInfo.fromJSON,
			callbacks,
		);
	}
	static async updateApiConfigurationProto(
		request: proto.dietcode.UpdateApiConfigurationRequest,
	): Promise<proto.dietcode.Empty> {
		return this.makeUnaryRequest(
			"updateApiConfigurationProto",
			request,
			proto.dietcode.UpdateApiConfigurationRequest.toJSON,
			proto.dietcode.Empty.fromJSON,
		);
	}
	static async updateApiConfiguration(
		request: proto.dietcode.UpdateApiConfigurationRequestNew,
	): Promise<proto.dietcode.Empty> {
		return this.makeUnaryRequest(
			"updateApiConfiguration",
			request,
			proto.dietcode.UpdateApiConfigurationRequestNew.toJSON,
			proto.dietcode.Empty.fromJSON,
		);
	}
	static async updateApiConfigurationPartial(
		request: proto.dietcode.UpdateApiConfigurationPartialRequest,
	): Promise<proto.dietcode.Empty> {
		return this.makeUnaryRequest(
			"updateApiConfigurationPartial",
			request,
			proto.dietcode.UpdateApiConfigurationPartialRequest.toJSON,
			proto.dietcode.Empty.fromJSON,
		);
	}
	static async refreshGroqModelsRpc(
		request: proto.dietcode.EmptyRequest,
	): Promise<proto.dietcode.OpenRouterCompatibleModelInfo> {
		return this.makeUnaryRequest(
			"refreshGroqModelsRpc",
			request,
			proto.dietcode.EmptyRequest.toJSON,
			proto.dietcode.OpenRouterCompatibleModelInfo.fromJSON,
		);
	}
	static async refreshBasetenModelsRpc(
		request: proto.dietcode.EmptyRequest,
	): Promise<proto.dietcode.OpenRouterCompatibleModelInfo> {
		return this.makeUnaryRequest(
			"refreshBasetenModelsRpc",
			request,
			proto.dietcode.EmptyRequest.toJSON,
			proto.dietcode.OpenRouterCompatibleModelInfo.fromJSON,
		);
	}
	static async getSapAiCoreModels(
		request: proto.dietcode.SapAiCoreModelsRequest,
	): Promise<proto.dietcode.SapAiCoreModelsResponse> {
		return this.makeUnaryRequest(
			"getSapAiCoreModels",
			request,
			proto.dietcode.SapAiCoreModelsRequest.toJSON,
			proto.dietcode.SapAiCoreModelsResponse.fromJSON,
		);
	}
	static async refreshOcaModels(
		request: proto.dietcode.StringRequest,
	): Promise<proto.dietcode.OcaCompatibleModelInfo> {
		return this.makeUnaryRequest(
			"refreshOcaModels",
			request,
			proto.dietcode.StringRequest.toJSON,
			proto.dietcode.OcaCompatibleModelInfo.fromJSON,
		);
	}
	static async getAihubmixModels(
		request: proto.dietcode.EmptyRequest,
	): Promise<proto.dietcode.OpenRouterCompatibleModelInfo> {
		return this.makeUnaryRequest(
			"getAihubmixModels",
			request,
			proto.dietcode.EmptyRequest.toJSON,
			proto.dietcode.OpenRouterCompatibleModelInfo.fromJSON,
		);
	}
	static async refreshVercelAiGatewayModelsRpc(
		request: proto.dietcode.EmptyRequest,
	): Promise<proto.dietcode.OpenRouterCompatibleModelInfo> {
		return this.makeUnaryRequest(
			"refreshVercelAiGatewayModelsRpc",
			request,
			proto.dietcode.EmptyRequest.toJSON,
			proto.dietcode.OpenRouterCompatibleModelInfo.fromJSON,
		);
	}
	static async refreshNousResearchModelsRpc(
		request: proto.dietcode.EmptyRequest,
	): Promise<proto.dietcode.OpenRouterCompatibleModelInfo> {
		return this.makeUnaryRequest(
			"refreshNousResearchModelsRpc",
			request,
			proto.dietcode.EmptyRequest.toJSON,
			proto.dietcode.OpenRouterCompatibleModelInfo.fromJSON,
		);
	}
}
export class OcaAccountServiceClient extends ProtoBusClient {
	static override serviceName: string = "dietcode.OcaAccountService";
	static async ocaAccountLoginClicked(
		request: proto.dietcode.EmptyRequest,
	): Promise<proto.dietcode.String> {
		return this.makeUnaryRequest(
			"ocaAccountLoginClicked",
			request,
			proto.dietcode.EmptyRequest.toJSON,
			proto.dietcode.String.fromJSON,
		);
	}
	static async ocaAccountLogoutClicked(
		request: proto.dietcode.EmptyRequest,
	): Promise<proto.dietcode.Empty> {
		return this.makeUnaryRequest(
			"ocaAccountLogoutClicked",
			request,
			proto.dietcode.EmptyRequest.toJSON,
			proto.dietcode.Empty.fromJSON,
		);
	}
	static ocaSubscribeToAuthStatusUpdate(
		request: proto.dietcode.EmptyRequest,
		callbacks: Callbacks<proto.dietcode.OcaAuthState>,
	): () => void {
		return this.makeStreamingRequest(
			"ocaSubscribeToAuthStatusUpdate",
			request,
			proto.dietcode.EmptyRequest.toJSON,
			proto.dietcode.OcaAuthState.fromJSON,
			callbacks,
		);
	}
}
export class SlashServiceClient extends ProtoBusClient {
	static override serviceName: string = "dietcode.SlashService";
	static async reportBug(
		request: proto.dietcode.StringRequest,
	): Promise<proto.dietcode.Empty> {
		return this.makeUnaryRequest(
			"reportBug",
			request,
			proto.dietcode.StringRequest.toJSON,
			proto.dietcode.Empty.fromJSON,
		);
	}
	static async condense(
		request: proto.dietcode.StringRequest,
	): Promise<proto.dietcode.Empty> {
		return this.makeUnaryRequest(
			"condense",
			request,
			proto.dietcode.StringRequest.toJSON,
			proto.dietcode.Empty.fromJSON,
		);
	}
	static async getAvailableSlashCommands(
		request: proto.dietcode.EmptyRequest,
	): Promise<proto.dietcode.SlashCommandsResponse> {
		return this.makeUnaryRequest(
			"getAvailableSlashCommands",
			request,
			proto.dietcode.EmptyRequest.toJSON,
			proto.dietcode.SlashCommandsResponse.fromJSON,
		);
	}
}
export class StateServiceClient extends ProtoBusClient {
	static override serviceName: string = "dietcode.StateService";
	static async getLatestState(
		request: proto.dietcode.EmptyRequest,
	): Promise<proto.dietcode.State> {
		return this.makeUnaryRequest(
			"getLatestState",
			request,
			proto.dietcode.EmptyRequest.toJSON,
			proto.dietcode.State.fromJSON,
		);
	}
	static async updateTerminalConnectionTimeout(
		request: proto.dietcode.UpdateTerminalConnectionTimeoutRequest,
	): Promise<proto.dietcode.UpdateTerminalConnectionTimeoutResponse> {
		return this.makeUnaryRequest(
			"updateTerminalConnectionTimeout",
			request,
			proto.dietcode.UpdateTerminalConnectionTimeoutRequest.toJSON,
			proto.dietcode.UpdateTerminalConnectionTimeoutResponse.fromJSON,
		);
	}
	static async updateTerminalReuseEnabled(
		request: proto.dietcode.BooleanRequest,
	): Promise<proto.dietcode.Empty> {
		return this.makeUnaryRequest(
			"updateTerminalReuseEnabled",
			request,
			proto.dietcode.BooleanRequest.toJSON,
			proto.dietcode.Empty.fromJSON,
		);
	}
	static async getAvailableTerminalProfiles(
		request: proto.dietcode.EmptyRequest,
	): Promise<proto.dietcode.TerminalProfiles> {
		return this.makeUnaryRequest(
			"getAvailableTerminalProfiles",
			request,
			proto.dietcode.EmptyRequest.toJSON,
			proto.dietcode.TerminalProfiles.fromJSON,
		);
	}
	static subscribeToState(
		request: proto.dietcode.EmptyRequest,
		callbacks: Callbacks<proto.dietcode.State>,
	): () => void {
		return this.makeStreamingRequest(
			"subscribeToState",
			request,
			proto.dietcode.EmptyRequest.toJSON,
			proto.dietcode.State.fromJSON,
			callbacks,
		);
	}
	static async toggleFavoriteModel(
		request: proto.dietcode.StringRequest,
	): Promise<proto.dietcode.Empty> {
		return this.makeUnaryRequest(
			"toggleFavoriteModel",
			request,
			proto.dietcode.StringRequest.toJSON,
			proto.dietcode.Empty.fromJSON,
		);
	}
	static async resetState(
		request: proto.dietcode.ResetStateRequest,
	): Promise<proto.dietcode.Empty> {
		return this.makeUnaryRequest(
			"resetState",
			request,
			proto.dietcode.ResetStateRequest.toJSON,
			proto.dietcode.Empty.fromJSON,
		);
	}
	static async togglePlanActModeProto(
		request: proto.dietcode.TogglePlanActModeRequest,
	): Promise<proto.dietcode.Boolean> {
		return this.makeUnaryRequest(
			"togglePlanActModeProto",
			request,
			proto.dietcode.TogglePlanActModeRequest.toJSON,
			proto.dietcode.Boolean.fromJSON,
		);
	}
	static async updateAutoApprovalSettings(
		request: proto.dietcode.AutoApprovalSettingsRequest,
	): Promise<proto.dietcode.Empty> {
		return this.makeUnaryRequest(
			"updateAutoApprovalSettings",
			request,
			proto.dietcode.AutoApprovalSettingsRequest.toJSON,
			proto.dietcode.Empty.fromJSON,
		);
	}
	static async updateSettings(
		request: proto.dietcode.UpdateSettingsRequest,
	): Promise<proto.dietcode.Empty> {
		return this.makeUnaryRequest(
			"updateSettings",
			request,
			proto.dietcode.UpdateSettingsRequest.toJSON,
			proto.dietcode.Empty.fromJSON,
		);
	}
	static async updateTaskSettings(
		request: proto.dietcode.UpdateTaskSettingsRequest,
	): Promise<proto.dietcode.Empty> {
		return this.makeUnaryRequest(
			"updateTaskSettings",
			request,
			proto.dietcode.UpdateTaskSettingsRequest.toJSON,
			proto.dietcode.Empty.fromJSON,
		);
	}
	static async updateTelemetrySetting(
		request: proto.dietcode.TelemetrySettingRequest,
	): Promise<proto.dietcode.Empty> {
		return this.makeUnaryRequest(
			"updateTelemetrySetting",
			request,
			proto.dietcode.TelemetrySettingRequest.toJSON,
			proto.dietcode.Empty.fromJSON,
		);
	}
	static async setWelcomeViewCompleted(
		request: proto.dietcode.BooleanRequest,
	): Promise<proto.dietcode.Empty> {
		return this.makeUnaryRequest(
			"setWelcomeViewCompleted",
			request,
			proto.dietcode.BooleanRequest.toJSON,
			proto.dietcode.Empty.fromJSON,
		);
	}
	static async updateInfoBannerVersion(
		request: proto.dietcode.Int64Request,
	): Promise<proto.dietcode.Empty> {
		return this.makeUnaryRequest(
			"updateInfoBannerVersion",
			request,
			proto.dietcode.Int64Request.toJSON,
			proto.dietcode.Empty.fromJSON,
		);
	}
	static async updateModelBannerVersion(
		request: proto.dietcode.Int64Request,
	): Promise<proto.dietcode.Empty> {
		return this.makeUnaryRequest(
			"updateModelBannerVersion",
			request,
			proto.dietcode.Int64Request.toJSON,
			proto.dietcode.Empty.fromJSON,
		);
	}
	static async updateCliBannerVersion(
		request: proto.dietcode.Int64Request,
	): Promise<proto.dietcode.Empty> {
		return this.makeUnaryRequest(
			"updateCliBannerVersion",
			request,
			proto.dietcode.Int64Request.toJSON,
			proto.dietcode.Empty.fromJSON,
		);
	}
	static async dismissBanner(
		request: proto.dietcode.StringRequest,
	): Promise<proto.dietcode.Empty> {
		return this.makeUnaryRequest(
			"dismissBanner",
			request,
			proto.dietcode.StringRequest.toJSON,
			proto.dietcode.Empty.fromJSON,
		);
	}
	static async trackBannerEvent(
		request: proto.dietcode.TrackBannerEventRequest,
	): Promise<proto.dietcode.Empty> {
		return this.makeUnaryRequest(
			"trackBannerEvent",
			request,
			proto.dietcode.TrackBannerEventRequest.toJSON,
			proto.dietcode.Empty.fromJSON,
		);
	}
	static async getProcessInfo(
		request: proto.dietcode.EmptyRequest,
	): Promise<proto.dietcode.ProcessInfo> {
		return this.makeUnaryRequest(
			"getProcessInfo",
			request,
			proto.dietcode.EmptyRequest.toJSON,
			proto.dietcode.ProcessInfo.fromJSON,
		);
	}
	static async flushPendingState(
		request: proto.dietcode.EmptyRequest,
	): Promise<proto.dietcode.Empty> {
		return this.makeUnaryRequest(
			"flushPendingState",
			request,
			proto.dietcode.EmptyRequest.toJSON,
			proto.dietcode.Empty.fromJSON,
		);
	}
	static async refreshRemoteConfig(
		request: proto.dietcode.EmptyRequest,
	): Promise<proto.dietcode.Empty> {
		return this.makeUnaryRequest(
			"refreshRemoteConfig",
			request,
			proto.dietcode.EmptyRequest.toJSON,
			proto.dietcode.Empty.fromJSON,
		);
	}
	static async testOtelConnection(
		request: proto.dietcode.EmptyRequest,
	): Promise<proto.dietcode.TestConnectionResult> {
		return this.makeUnaryRequest(
			"testOtelConnection",
			request,
			proto.dietcode.EmptyRequest.toJSON,
			proto.dietcode.TestConnectionResult.fromJSON,
		);
	}
	static async testPromptUploading(
		request: proto.dietcode.EmptyRequest,
	): Promise<proto.dietcode.TestConnectionResult> {
		return this.makeUnaryRequest(
			"testPromptUploading",
			request,
			proto.dietcode.EmptyRequest.toJSON,
			proto.dietcode.TestConnectionResult.fromJSON,
		);
	}
}
export class TaskServiceClient extends ProtoBusClient {
	static override serviceName: string = "dietcode.TaskService";
	static async cancelTask(
		request: proto.dietcode.EmptyRequest,
	): Promise<proto.dietcode.Empty> {
		return this.makeUnaryRequest(
			"cancelTask",
			request,
			proto.dietcode.EmptyRequest.toJSON,
			proto.dietcode.Empty.fromJSON,
		);
	}
	static async cancelBackgroundCommand(
		request: proto.dietcode.EmptyRequest,
	): Promise<proto.dietcode.Empty> {
		return this.makeUnaryRequest(
			"cancelBackgroundCommand",
			request,
			proto.dietcode.EmptyRequest.toJSON,
			proto.dietcode.Empty.fromJSON,
		);
	}
	static async clearTask(
		request: proto.dietcode.EmptyRequest,
	): Promise<proto.dietcode.Empty> {
		return this.makeUnaryRequest(
			"clearTask",
			request,
			proto.dietcode.EmptyRequest.toJSON,
			proto.dietcode.Empty.fromJSON,
		);
	}
	static async getTotalTasksSize(
		request: proto.dietcode.EmptyRequest,
	): Promise<proto.dietcode.Int64> {
		return this.makeUnaryRequest(
			"getTotalTasksSize",
			request,
			proto.dietcode.EmptyRequest.toJSON,
			proto.dietcode.Int64.fromJSON,
		);
	}
	static async deleteTasksWithIds(
		request: proto.dietcode.StringArrayRequest,
	): Promise<proto.dietcode.Empty> {
		return this.makeUnaryRequest(
			"deleteTasksWithIds",
			request,
			proto.dietcode.StringArrayRequest.toJSON,
			proto.dietcode.Empty.fromJSON,
		);
	}
	static async newTask(
		request: proto.dietcode.NewTaskRequest,
	): Promise<proto.dietcode.String> {
		return this.makeUnaryRequest(
			"newTask",
			request,
			proto.dietcode.NewTaskRequest.toJSON,
			proto.dietcode.String.fromJSON,
		);
	}
	static async showTaskWithId(
		request: proto.dietcode.StringRequest,
	): Promise<proto.dietcode.TaskResponse> {
		return this.makeUnaryRequest(
			"showTaskWithId",
			request,
			proto.dietcode.StringRequest.toJSON,
			proto.dietcode.TaskResponse.fromJSON,
		);
	}
	static async exportTaskWithId(
		request: proto.dietcode.StringRequest,
	): Promise<proto.dietcode.Empty> {
		return this.makeUnaryRequest(
			"exportTaskWithId",
			request,
			proto.dietcode.StringRequest.toJSON,
			proto.dietcode.Empty.fromJSON,
		);
	}
	static async toggleTaskFavorite(
		request: proto.dietcode.TaskFavoriteRequest,
	): Promise<proto.dietcode.Empty> {
		return this.makeUnaryRequest(
			"toggleTaskFavorite",
			request,
			proto.dietcode.TaskFavoriteRequest.toJSON,
			proto.dietcode.Empty.fromJSON,
		);
	}
	static async getTaskHistory(
		request: proto.dietcode.GetTaskHistoryRequest,
	): Promise<proto.dietcode.TaskHistoryArray> {
		return this.makeUnaryRequest(
			"getTaskHistory",
			request,
			proto.dietcode.GetTaskHistoryRequest.toJSON,
			proto.dietcode.TaskHistoryArray.fromJSON,
		);
	}
	static async askResponse(
		request: proto.dietcode.AskResponseRequest,
	): Promise<proto.dietcode.Empty> {
		return this.makeUnaryRequest(
			"askResponse",
			request,
			proto.dietcode.AskResponseRequest.toJSON,
			proto.dietcode.Empty.fromJSON,
		);
	}
	static async taskFeedback(
		request: proto.dietcode.StringRequest,
	): Promise<proto.dietcode.Empty> {
		return this.makeUnaryRequest(
			"taskFeedback",
			request,
			proto.dietcode.StringRequest.toJSON,
			proto.dietcode.Empty.fromJSON,
		);
	}
	static async taskCompletionViewChanges(
		request: proto.dietcode.Int64Request,
	): Promise<proto.dietcode.Empty> {
		return this.makeUnaryRequest(
			"taskCompletionViewChanges",
			request,
			proto.dietcode.Int64Request.toJSON,
			proto.dietcode.Empty.fromJSON,
		);
	}
	static async executeQuickWin(
		request: proto.dietcode.ExecuteQuickWinRequest,
	): Promise<proto.dietcode.Empty> {
		return this.makeUnaryRequest(
			"executeQuickWin",
			request,
			proto.dietcode.ExecuteQuickWinRequest.toJSON,
			proto.dietcode.Empty.fromJSON,
		);
	}
	static async deleteAllTaskHistory(
		request: proto.dietcode.EmptyRequest,
	): Promise<proto.dietcode.DeleteAllTaskHistoryCount> {
		return this.makeUnaryRequest(
			"deleteAllTaskHistory",
			request,
			proto.dietcode.EmptyRequest.toJSON,
			proto.dietcode.DeleteAllTaskHistoryCount.fromJSON,
		);
	}
	static async explainChanges(
		request: proto.dietcode.ExplainChangesRequest,
	): Promise<proto.dietcode.Empty> {
		return this.makeUnaryRequest(
			"explainChanges",
			request,
			proto.dietcode.ExplainChangesRequest.toJSON,
			proto.dietcode.Empty.fromJSON,
		);
	}
}
export class UiServiceClient extends ProtoBusClient {
	static override serviceName: string = "dietcode.UiService";
	static async scrollToSettings(
		request: proto.dietcode.StringRequest,
	): Promise<proto.dietcode.KeyValuePair> {
		return this.makeUnaryRequest(
			"scrollToSettings",
			request,
			proto.dietcode.StringRequest.toJSON,
			proto.dietcode.KeyValuePair.fromJSON,
		);
	}
	static async onDidShowAnnouncement(
		request: proto.dietcode.EmptyRequest,
	): Promise<proto.dietcode.Boolean> {
		return this.makeUnaryRequest(
			"onDidShowAnnouncement",
			request,
			proto.dietcode.EmptyRequest.toJSON,
			proto.dietcode.Boolean.fromJSON,
		);
	}
	static subscribeToAddToInput(
		request: proto.dietcode.EmptyRequest,
		callbacks: Callbacks<proto.dietcode.String>,
	): () => void {
		return this.makeStreamingRequest(
			"subscribeToAddToInput",
			request,
			proto.dietcode.EmptyRequest.toJSON,
			proto.dietcode.String.fromJSON,
			callbacks,
		);
	}
	static subscribeToMcpButtonClicked(
		request: proto.dietcode.EmptyRequest,
		callbacks: Callbacks<proto.dietcode.Empty>,
	): () => void {
		return this.makeStreamingRequest(
			"subscribeToMcpButtonClicked",
			request,
			proto.dietcode.EmptyRequest.toJSON,
			proto.dietcode.Empty.fromJSON,
			callbacks,
		);
	}
	static subscribeToHistoryButtonClicked(
		request: proto.dietcode.EmptyRequest,
		callbacks: Callbacks<proto.dietcode.Empty>,
	): () => void {
		return this.makeStreamingRequest(
			"subscribeToHistoryButtonClicked",
			request,
			proto.dietcode.EmptyRequest.toJSON,
			proto.dietcode.Empty.fromJSON,
			callbacks,
		);
	}
	static subscribeToChatButtonClicked(
		request: proto.dietcode.EmptyRequest,
		callbacks: Callbacks<proto.dietcode.Empty>,
	): () => void {
		return this.makeStreamingRequest(
			"subscribeToChatButtonClicked",
			request,
			proto.dietcode.EmptyRequest.toJSON,
			proto.dietcode.Empty.fromJSON,
			callbacks,
		);
	}
	static subscribeToAccountButtonClicked(
		request: proto.dietcode.EmptyRequest,
		callbacks: Callbacks<proto.dietcode.Empty>,
	): () => void {
		return this.makeStreamingRequest(
			"subscribeToAccountButtonClicked",
			request,
			proto.dietcode.EmptyRequest.toJSON,
			proto.dietcode.Empty.fromJSON,
			callbacks,
		);
	}
	static subscribeToSettingsButtonClicked(
		request: proto.dietcode.EmptyRequest,
		callbacks: Callbacks<proto.dietcode.Empty>,
	): () => void {
		return this.makeStreamingRequest(
			"subscribeToSettingsButtonClicked",
			request,
			proto.dietcode.EmptyRequest.toJSON,
			proto.dietcode.Empty.fromJSON,
			callbacks,
		);
	}
	static subscribeToWorktreesButtonClicked(
		request: proto.dietcode.EmptyRequest,
		callbacks: Callbacks<proto.dietcode.Empty>,
	): () => void {
		return this.makeStreamingRequest(
			"subscribeToWorktreesButtonClicked",
			request,
			proto.dietcode.EmptyRequest.toJSON,
			proto.dietcode.Empty.fromJSON,
			callbacks,
		);
	}
	static subscribeToJoyZoningButtonClicked(
		request: proto.dietcode.EmptyRequest,
		callbacks: Callbacks<proto.dietcode.Empty>,
	): () => void {
		return this.makeStreamingRequest(
			"subscribeToJoyZoningButtonClicked",
			request,
			proto.dietcode.EmptyRequest.toJSON,
			proto.dietcode.Empty.fromJSON,
			callbacks,
		);
	}
	static subscribeToPartialMessage(
		request: proto.dietcode.EmptyRequest,
		callbacks: Callbacks<proto.dietcode.DietCodeMessage>,
	): () => void {
		return this.makeStreamingRequest(
			"subscribeToPartialMessage",
			request,
			proto.dietcode.EmptyRequest.toJSON,
			proto.dietcode.DietCodeMessage.fromJSON,
			callbacks,
		);
	}
	static async initializeWebview(
		request: proto.dietcode.EmptyRequest,
	): Promise<proto.dietcode.Empty> {
		return this.makeUnaryRequest(
			"initializeWebview",
			request,
			proto.dietcode.EmptyRequest.toJSON,
			proto.dietcode.Empty.fromJSON,
		);
	}
	static subscribeToRelinquishControl(
		request: proto.dietcode.EmptyRequest,
		callbacks: Callbacks<proto.dietcode.Empty>,
	): () => void {
		return this.makeStreamingRequest(
			"subscribeToRelinquishControl",
			request,
			proto.dietcode.EmptyRequest.toJSON,
			proto.dietcode.Empty.fromJSON,
			callbacks,
		);
	}
	static subscribeToShowWebview(
		request: proto.dietcode.EmptyRequest,
		callbacks: Callbacks<proto.dietcode.ShowWebviewEvent>,
	): () => void {
		return this.makeStreamingRequest(
			"subscribeToShowWebview",
			request,
			proto.dietcode.EmptyRequest.toJSON,
			proto.dietcode.ShowWebviewEvent.fromJSON,
			callbacks,
		);
	}
	static async openUrl(
		request: proto.dietcode.StringRequest,
	): Promise<proto.dietcode.Empty> {
		return this.makeUnaryRequest(
			"openUrl",
			request,
			proto.dietcode.StringRequest.toJSON,
			proto.dietcode.Empty.fromJSON,
		);
	}
	static async openWalkthrough(
		request: proto.dietcode.EmptyRequest,
	): Promise<proto.dietcode.Empty> {
		return this.makeUnaryRequest(
			"openWalkthrough",
			request,
			proto.dietcode.EmptyRequest.toJSON,
			proto.dietcode.Empty.fromJSON,
		);
	}
	static async onSuggestionClicked(
		request: proto.dietcode.StringRequest,
	): Promise<proto.dietcode.Empty> {
		return this.makeUnaryRequest(
			"onSuggestionClicked",
			request,
			proto.dietcode.StringRequest.toJSON,
			proto.dietcode.Empty.fromJSON,
		);
	}
}
export class WebServiceClient extends ProtoBusClient {
	static override serviceName: string = "dietcode.WebService";
	static async checkIsImageUrl(
		request: proto.dietcode.StringRequest,
	): Promise<proto.dietcode.IsImageUrl> {
		return this.makeUnaryRequest(
			"checkIsImageUrl",
			request,
			proto.dietcode.StringRequest.toJSON,
			proto.dietcode.IsImageUrl.fromJSON,
		);
	}
	static async fetchOpenGraphData(
		request: proto.dietcode.StringRequest,
	): Promise<proto.dietcode.OpenGraphData> {
		return this.makeUnaryRequest(
			"fetchOpenGraphData",
			request,
			proto.dietcode.StringRequest.toJSON,
			proto.dietcode.OpenGraphData.fromJSON,
		);
	}
	static async openInBrowser(
		request: proto.dietcode.StringRequest,
	): Promise<proto.dietcode.Empty> {
		return this.makeUnaryRequest(
			"openInBrowser",
			request,
			proto.dietcode.StringRequest.toJSON,
			proto.dietcode.Empty.fromJSON,
		);
	}
}
export class WorktreeServiceClient extends ProtoBusClient {
	static override serviceName: string = "dietcode.WorktreeService";
	static async listWorktrees(
		request: proto.dietcode.EmptyRequest,
	): Promise<proto.dietcode.WorktreeList> {
		return this.makeUnaryRequest(
			"listWorktrees",
			request,
			proto.dietcode.EmptyRequest.toJSON,
			proto.dietcode.WorktreeList.fromJSON,
		);
	}
	static async createWorktree(
		request: proto.dietcode.CreateWorktreeRequest,
	): Promise<proto.dietcode.WorktreeResult> {
		return this.makeUnaryRequest(
			"createWorktree",
			request,
			proto.dietcode.CreateWorktreeRequest.toJSON,
			proto.dietcode.WorktreeResult.fromJSON,
		);
	}
	static async deleteWorktree(
		request: proto.dietcode.DeleteWorktreeRequest,
	): Promise<proto.dietcode.WorktreeResult> {
		return this.makeUnaryRequest(
			"deleteWorktree",
			request,
			proto.dietcode.DeleteWorktreeRequest.toJSON,
			proto.dietcode.WorktreeResult.fromJSON,
		);
	}
	static async switchWorktree(
		request: proto.dietcode.SwitchWorktreeRequest,
	): Promise<proto.dietcode.WorktreeResult> {
		return this.makeUnaryRequest(
			"switchWorktree",
			request,
			proto.dietcode.SwitchWorktreeRequest.toJSON,
			proto.dietcode.WorktreeResult.fromJSON,
		);
	}
	static async getAvailableBranches(
		request: proto.dietcode.EmptyRequest,
	): Promise<proto.dietcode.BranchList> {
		return this.makeUnaryRequest(
			"getAvailableBranches",
			request,
			proto.dietcode.EmptyRequest.toJSON,
			proto.dietcode.BranchList.fromJSON,
		);
	}
	static async getWorktreeDefaults(
		request: proto.dietcode.EmptyRequest,
	): Promise<proto.dietcode.WorktreeDefaults> {
		return this.makeUnaryRequest(
			"getWorktreeDefaults",
			request,
			proto.dietcode.EmptyRequest.toJSON,
			proto.dietcode.WorktreeDefaults.fromJSON,
		);
	}
	static async getWorktreeIncludeStatus(
		request: proto.dietcode.EmptyRequest,
	): Promise<proto.dietcode.WorktreeIncludeStatus> {
		return this.makeUnaryRequest(
			"getWorktreeIncludeStatus",
			request,
			proto.dietcode.EmptyRequest.toJSON,
			proto.dietcode.WorktreeIncludeStatus.fromJSON,
		);
	}
	static async createWorktreeInclude(
		request: proto.dietcode.CreateWorktreeIncludeRequest,
	): Promise<proto.dietcode.WorktreeResult> {
		return this.makeUnaryRequest(
			"createWorktreeInclude",
			request,
			proto.dietcode.CreateWorktreeIncludeRequest.toJSON,
			proto.dietcode.WorktreeResult.fromJSON,
		);
	}
	static async checkoutBranch(
		request: proto.dietcode.CheckoutBranchRequest,
	): Promise<proto.dietcode.WorktreeResult> {
		return this.makeUnaryRequest(
			"checkoutBranch",
			request,
			proto.dietcode.CheckoutBranchRequest.toJSON,
			proto.dietcode.WorktreeResult.fromJSON,
		);
	}
	static async mergeWorktree(
		request: proto.dietcode.MergeWorktreeRequest,
	): Promise<proto.dietcode.MergeWorktreeResult> {
		return this.makeUnaryRequest(
			"mergeWorktree",
			request,
			proto.dietcode.MergeWorktreeRequest.toJSON,
			proto.dietcode.MergeWorktreeResult.fromJSON,
		);
	}
	static async trackWorktreeViewOpened(
		request: proto.dietcode.TrackWorktreeViewOpenedRequest,
	): Promise<proto.dietcode.Empty> {
		return this.makeUnaryRequest(
			"trackWorktreeViewOpened",
			request,
			proto.dietcode.TrackWorktreeViewOpenedRequest.toJSON,
			proto.dietcode.Empty.fromJSON,
		);
	}
}
